### ISSUE TITLE
Why is Google Now suggesting your GitHub to me?

### ISSUE THREAD

**Issue by Ralithune** [gauravat16/Bash-Scripts#1]
I Google bash stuff sometimes but this is weird.  Google Now's feed put your GitHub up for me.
![Screenshot_20190825-215528](https://user-images.githubusercontent.com/12363715/63666169-4e4fb300-c783-11e9-8a6e-da3f591575a1.png)

**Comment by Ralithune** [comment]
I'm not actually asking, for the record - just sharing what I thought was a weird and noteworthy experience.

**Comment by gauravat16** [comment]
Do you use reddit? /r/Ubuntu?

**Comment by Ralithune** [comment]
I don't.  I know, sacrilege; but Reddit's UI has always been a massive dumpster fire to me.

**Comment by gauravat16** [comment]
Yeah Its a mess. I posted a link there. I thought you were a member of that subreddit and might have clicked on the post.

Our overlord google works in mysterious ways.
